version: 1.0.{build}
branches:
  only:
    - master
skip_commits:
  message: /Updated.*\.(md)/

image: Visual Studio 2015

deploy:
  - provider: WebDeploy
    server: "https://dev-pricing.westeurope.cloudapp.azure.com:8172/MsDeploy.axd"
    website: OktaAuth
    username: agent-deploy
    password:
      secure: JgjViYedUd5IyB5V8dmwzPCt5qAAmxjM5fDd/ZZKAGc=
    ntlm: false
    remove_files: false
    app_offline: false
    do_not_use_checksum: true
    sync_retry_attempts: 2
    sync_retry_interval: 2000
    artifact: Okta.OAuth.CodeFlow.zip
