version: 1.0.{build}
branches:
  only:
    - master
skip_commits:
  message: /Updated.*\.(md)/

environment:
  ARTIFACT_DESTINATION: out
  OKTAOAUTH_ARTIFACT: Okta.OAuth.CodeFlow.zip
  OKTAOAUTHAPI_ARTIFACT: Okta.OAuth.Api.zip
  API_TOKEN:
    secure: K+Xh6Wc8vsAuJqeqdlNKh8ie7E1prS/yJ3XFQyGuHI8=
  DEPLOY_PASS:
    secure: WeGA/eDEl6L8VvlD+VzqgiJI3WDrbmAzEGWIeaEDh7Q=

build_script:
  - ps: . .\download-artifact.ps1
            -projectSlug okta-oauth
            -artifactName $env:OKTAOAUTH_ARTIFACT
            -destinationDir $env:ARTIFACT_DESTINATION
            -apiToken $env:API_TOKEN
  - ps: . .\download-artifact.ps1
            -projectSlug okta-oauth
            -artifactName $env:OKTAOAUTHAPI_ARTIFACT
            -destinationDir $env:ARTIFACT_DESTINATION
            -apiToken $env:API_TOKEN

# Specify the artifacts to be uploaded for this build, so that deploy can pick up.
# Specify zip artifact is Web Deploy package, not a regular zip archive
artifacts:
  - path: '%ARTIFACT_DESTINATION%\%OKTAOAUTH_ARTIFACT%'
    name: OktaOAuth
    type: WebDeployPackage

  - path: '%ARTIFACT_DESTINATION%\%OKTAOAUTHAPI_ARTIFACT%'
    name: OktaOAuthApi
    type: WebDeployPackage

deploy:
  - provider: WebDeploy
    server: "https://dev-pricing.westeurope.cloudapp.azure.com:8172/MsDeploy.axd"
    website: OktaAuth
    username: agent-deploy
    password:
      secure: WeGA/eDEl6L8VvlD+VzqgiJI3WDrbmAzEGWIeaEDh7Q=
    ntlm: false
    remove_files: false
    app_offline: false
    do_not_use_checksum: true
    sync_retry_attempts: 2
    sync_retry_interval: 2000
    artifact: OktaOAuth

  - provider: WebDeploy
    server: "https://dev-pricing.westeurope.cloudapp.azure.com:8172/MsDeploy.axd"
    website: OktaOAuthApi
    username: agent-deploy
    password:
      secure: WeGA/eDEl6L8VvlD+VzqgiJI3WDrbmAzEGWIeaEDh7Q=
    ntlm: false
    remove_files: false
    app_offline: false
    do_not_use_checksum: true
    sync_retry_attempts: 2
    sync_retry_interval: 2000
    artifact: OktaOAuthApi

# deploy_script:
#   - ps: .\deploy.ps1
#             -appName OktaOAuth
#             -packageSource $env:ARTIFACT_DESTINATION
#             -server dev-pricing.westeurope.cloudapp.azure.com
#             -deployUser agent-deploy
#             -deployPass $env:DEPLOY_PASS
