version: 1.0.{build}
branches:
  only:
    - master
skip_commits:
  message: /Updated.*\.(md)/

build_script:
  - ps: . .\download-artifact.ps1 -projectSlug okta-oauth -destination env:ARTIFACT_DESTINATION -apiToken env:API_TOKEN

deploy:
  - provider: WebDeploy
    server: "https://dev-pricing.westeurope.cloudapp.azure.com:8172/MsDeploy.axd"
    website: OktaAuth
    username: agent-deploy
    password:
      secure: JgjViYedUd5IyB5V8dmwzPCt5qAAmxjM5fDd/ZZKAGc=
    ntlm: false
    remove_files: false
    app_offline: false
    do_not_use_checksum: true
    sync_retry_attempts: 2
    sync_retry_interval: 2000
    artifact: C:\projects\Okta.OAuth.CodeFlow.zip

environment:
  ARTIFACT_DESTINATION: C:\projects\Okta.OAuth.CodeFlow.zip
  API_TOKEN:
    secure: K+Xh6Wc8vsAuJqeqdlNKh8ie7E1prS/yJ3XFQyGuHI8=
